model: ps

model_params:
  freq: B
  normalization: longmean
  context_length: 210 # 360 for `D`
  prediction_length: 30 # 30 for `D`
  matching: ot

  iterations: 4
  alpha: 0.005
  noise_level: 0.5
  guidance_scale: 4

dataset_params:
  dataset: exchange_rate_nips
  num_batches_per_epoch: 128
  batch_size: 64

seed: 6432