model: conditional
setting: multivariate
model_params:
  backbone_params:
    input_dim: 1
    output_dim: 1
    step_emb: 64
    num_residual_blocks: 3
    residual_block: s4
    hidden_dim: 64
    dropout: 0.0
    init_skip: False
    feature_skip: True

  freq: H
  normalization: longmean
  context_length: 24 # 360 for `D`
  prediction_length: 24 # 30 for `D`
 
  use_ema: True
  use_lags: True
  
  num_steps: 32
  solver: euler
  matching: random

  device: cuda:0
  prior_name: Q0DistMultiTask
  trained_prior: True
    
  optimizer_params: 
    lr: 1.e-3

  prior_params:
    kernel: ou
    gamma: 1
    iso: 0.001
    context_freqs: 7

  ema_params: 
    beta: 0.9999
    update_after_step: 128
    update_every: 2


dataset_params:
  dataset: weather
  num_batches_per_epoch: 128
  batch_size: 1

trainer_params:
  gradient_clip_val: .5
  max_epochs: 400
  num_sanity_val_steps: 0

# Used only in callback,
# the final evaluation uses 100 samples
evaluation_params:
  num_samples: 50
  use_validation_set: True
  eval_every: 10
  do_final_eval: True

seed: 6433
